---
- hosts: local
  gather_facts: false
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
  - name: Install dependent roles & collections
    command: ansible-galaxy install -i -r ../requirements.yml

- hosts: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    nameservers:
    - 1.1.1.1
    search_domains:
    - local
    hypriot_flash_url: https://raw.githubusercontent.com/hypriot/flash/master/flash

    # yamllint disable rule:line-length
    ubuntu_image_url: >-
      https://cdimage.ubuntu.com/releases/20.04.2/release/ubuntu-20.04.2-preinstalled-server-arm64+raspi.img.xz
    raspios_lite_image_url: >-
      https://github.com/timebertt/pi-cloud-init/releases/download/2021-05-10/2021-05-10-raspios-buster-aarch64-lite-cloud-init.zip
    # yamllint enable rule:line-length

  vars_prompt:
  - name: gh_username
    prompt: What is your github user name?
    private: false

  - name: node_ip
    prompt: What static IPv4 address do you want to assign to this node?
    private: false

  - name: gateway_ip
    prompt: What gateway IPv4 address do you want to assign to this node?
    private: false

  - name: hostname
    prompt: What hostname do you want to assign to this device?
    private: false

  - name: username
    prompt: What username do you want to use on this device?
    private: false

  - name: run_rpi_boot
    prompt: Do you want to run RPi USBBoot?
    private: false

  - name: os_choice
    prompt: Which OS do you want to load (Ubuntu/RaspiOSLite)?
    private: false

  pre_tasks:
  - name: Validate provided IPv4 addresses
    fail:
      msg: >-
        IPv4 address {{ item.ip }} for {{ item.name }} is invalid
    with_items:
    - {name: node_ip, ip: '{{ node_ip }}'}
    - {name: gateway_ip, ip: '{{ gateway_ip }}'}
    when: not item.ip is regex('^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$')
    run_once: true

  - name: Validate provided node hostname
    fail:
      msg: >-
        Hostname {{ hostname }} is invalid
    # yamllint disable-line rule:line-length
    when: not hostname is regex('^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$')
    run_once: true

  - name: Validate truthiness of run_rpi_boot
    fail:
      msg: Value of run_rpi_boot ({{ run_rpi_boot }}) is not truthy or falsy
    when: not ( ( run_rpi_boot is truthy(convert_bool=True) ) or ( run_rpi_boot is falsy(convert_bool=True) ) )
    run_once: true

  - name: Validate OS choice
    fail:
      msg: Value of os_choice ({{ os_choice }}) is not Ubuntu or RaspiOSLite
    when: not os_choice is regex('^(?i)(ubuntu|raspioslite)$')

  - name: Set OS image URL to Ubuntu
    set_fact:
      node_os_url: '{{ ubuntu_image_url }}'
    when: os_choice is regex('^(?i)ubuntu$')

  - name: Set OS image URL to RaspiOSLite
    set_fact:
      node_os_url: '{{ raspios_lite_image_url }}'
    when: os_choice is regex('^(?i)raspioslite$')

  gather_facts: true

  roles:
  - role: rpi_boot
    when: run_rpi_boot is truthy(convert_bool=True)
  - role: hypriot_flash
  - role: create_node
